services:
  php-ap:
    container_name: php-ap
    build: ./build/php-ap
    image: php-ap
    restart: always
    deploy:
      resources:
        limits:
          memory: 200m
    logging:
      options:
        max-size: 100k
        max-file: 3
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php-db
  php-db:
    container_name: php-db
    image: mysql:5.7
    restart: always
    deploy:
      resources:
        limits:
          memory: 300m
    logging:
      options:
        max-size: 100k
        max-file: 3
    volumes:
      - php-db_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
volumes:
  php-db_mysql:
    name: php-db_mysql
